CREATE TABLE sboard2(
ID NUMBER NOT NULL,
APP_USER_ID NUMBER NOT NULL,
BTITLE VARCHAR2(1000) NOT NULL,
BCONTENT CLOB NOT NULL,
BPASS VARCHAR2(255) NOT NULL,
BFILE VARCHAR2(255),
BHIT NUMBER,
BIP VARCHAR2(255) NOT NULL,
CREATED_AT DATE
);
desc sboard2;
create sequence sboard2_seq;